name: test-app
version: 1.0.0

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
     - "8000:8000"
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: test
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis-service:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    

  
  